
name: SAST with Bandit

on:
  push:
    branches: ['main']
  workflow_dispatch:
  ## Start: Version 3
  #pull_request:
  #  types: [opened, reopened, synchronize]
  ## End: Version 3

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      ## Start: Version 0
      - name: Checkout repository
        uses: actions/checkout@v3
      ## End: Version 0



      ## Start: Version 1
      #- name: Install dependencies
      #  shell: bash
      #  run: |
      #    pip install bandit

      #- name: Bandit
      #  shell: bash
      #  run: |
      #    bandit -r .
      ## End: Version 1





      ## Start: Version 2
      - name: Install dependencies
        shell: bash
        run: |
          pip install bandit-sarif-formatter bandit

      - name: Bandit
        shell: bash
        run: |
          bandit -f sarif -o results.sarif -r --exit-zero .
        
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: results.sarif
          path: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
      ## End: Version 2