name: Secrets scanning with GitLeaks

on:
  push:
    branches: ['main']
  workflow_dispatch:
  ## Start: Version 3
  pull_request:
    types: [opened, reopened, synchronize]
  ## End: Version 3

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      ## Start: Version 0
      - name: Checkout repository
        uses: actions/checkout@v3
      ## End: Version 0




      ## Start: Version 1
      #- name: GitLeaks
      #  uses: gitleaks/gitleaks-action@v2
      ## End: Version 1




      ## Start: Version 2
      - name: GitLeaks
        continue-on-error: true
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
           name: results.sarif
           path: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
      ## End: Version 2
